### ISSUE TITLE
Have the items of the panel and systray (menus, icons,...) in white rather than grey (gnome shell theme)

### ISSUE THREAD

**Issue by Tuxman2** [etiennegnome/LinMOS#2]
Hello,

I would like to see the items menu (characters, icons) in white rather than grey for LinMOS Gnome shell theme. How to change it ? See the pictures.

![SystrayPict2](https://user-images.githubusercontent.com/23556606/107505402-8a9fea80-6b94-11eb-8987-a966d7cfe4d7.png)
![SystrayPict3](https://user-images.githubusercontent.com/23556606/107505429-95f31600-6b94-11eb-9c50-ee4d4916ed6a.png)
![SystrayPict4](https://user-images.githubusercontent.com/23556606/107505434-97bcd980-6b94-11eb-9b1c-b80581e1217a.png)
![PanelPicture](https://user-images.githubusercontent.com/23556606/107505445-9c818d80-6b94-11eb-8006-ae92dc5a05ec.png)

Thanks.

Note: I use the LinMOS-solid-blue 1.5 version theme (gtk 3.0 and gnome shell) and I'm on Manjaro Gnome under Wayland.

**Comment by etiennegnome** [comment]
Hey Tuxman2,

The screenshots you sent don't seem to match the Gnome-shell LinMOS 1.5 theme.

This is what the Gnome-shell Sensory Perception extension looks like with LinMOS 1.5.
![Capture d’écran de 2021-02-11 01-12-28](https://user-images.githubusercontent.com/75214711/107591180-61ba3c80-6c0a-11eb-9b95-7dfefae184d5.jpg)

You can see all the differences between your screenshot and mine.

My Gnome instance is version 3.36.8 (UBUNTU 20.04.2) under X.org, with X.org graphics driver for NVidia.
I don't use proprietary NVIDIA drivers because they disturb transparency and ultimately don't give me more performance (I'm not a gamer).
I tested with Gnome version 3.38, and the rendering is the same as with version 3.36.
I also tested in Wayland, and the rendering is identical to that in X.org.

For me, it looks like you're not using the LinMOS theme for Gnome-shell.

Regards

**Comment by etiennegnome** [comment]
Hey Tuxman2,

The screenshots you sent don't seem to match the Gnome-shell LinMOS 1.5 
theme.

This is what the Gnome-shell Sensory Perception extension looks like 
with LinMOS 1.5.


You can see all the differences between your screenshot and mine.

My Gnome instance is version 3.36.8 (UBUNTU 20.04.2) under X.org, with 
X.org graphics driver for NVidia.
I don't use proprietary NVIDIA drivers because they disturb transparency 
and ultimately don't give me more performance (I'm not a gamer).
I tested with Gnome version 3.38, and the rendering is the same as with 
version 3.36.
I also tested in Wayland, and the rendering is identical to that in X.org.

For me, it looks like you're not using the LinMOS theme for Gnome-shell.

Regards

**Comment by Tuxman2** [comment]
Hi etiennegnome,

where did you put your theme file? I placed it in the hidden Themes directory in my home folder. Perhaps it is not the right location. Well, I will erase all others gnome shell theme I have installed and use your gnome shell theme only. I will tell you if it works or not later. For your information, I'm on Manjaro Gnome 20.2.1 and Gnome 3.38.x with Wayland by default.

Regards.

**Comment by etiennegnome** [comment]
Hey,

You need to unzip the whole folder 'LINMOS-Blue-Solid-1.5.tar.xz' in 
your .themes directory.
There should only be one LINMOS-Blue-Solid-1.5 directory in your .themes.
In this LINMOS-Blue-Solid-1.5 directory, you will find gnome-shell and 
gtk-3.0 subdirectories.
You will thus find and select the LINMOS-Blue-Solid-1.5 theme in the 
'Applications' and 'Shell' comboboxes in gnome-tweaks.
That's all.

Regards.

Le 11/02/2021 à 13:41, Tuxman2 a écrit :

**Comment by Tuxman2** [comment]
Hi, 

That's what I did, but it doesn't look like as your screenshot.

I would like to modify the color of these elements (see my screenshots) in white by modifying your source code.  Can you indicate me the parts of your source code where the color for these elements is defined ?

Thanks.

Regards.

**Comment by etiennegnome** [comment]
Hey Tuxman2,

All selected buttons, menus, menus items, and so on, have there color 
already set to #eeeeec.
It's not white, but the color is light enough to not look like dark gray 
or even gray.

So the problem is not with the theme.
The problem comes from your config.
I think you didn't tweak Gnome to use the right theme with Gnome-shell.

Are you using gnome-tweaks to set Gnome-shell theme and Apps themes ?
You can see gnome-tweaks in action on my screenshot.
To be able to configure Gnome-shell theme in gnome-tweaks, you have to 
go to the Gnome-shell extensions site (https://extensions.gnome.org/), 
and install the 'User Themes' extension.

Many tutorials exist on the internet to help you install what you need, 
and correctly, to customize Gnome.

Regards.

Le 14/02/2021 à 13:24, Tuxman2 a écrit :

**Comment by Tuxman2** [comment]
Hi etiennegnome,

thanks to give me the value of the color for the items.

I always use the gnome-tweaks tool to set the appearance, and I set gnome-shell part like you. The 'user themes' extension is installed by default on Manjaro Gnome but I didn't check if it is enabled.

Otherwise, thanks for your help. ;-)

Regards.
